# Generated by Django 2.1.2 on 2019-01-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20190116_1139'),
        ('comment', '0002_auto_20190116_1329'),
    ]

    operations = [
    ]
